"""Digest Generator: creates daily markdown digests of AI news and tool evaluations."""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

from src.models import RankedItem, TestResult, TestVerdict

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).parent.parent.parent / "output" / "digests"


def generate_digest(
    ranked: list[RankedItem],
    test_results: list[TestResult] | None = None,
    run_date: date | None = None,
    max_items: int = 20,
) -> str:
    """Generate a daily markdown digest.

    Args:
        ranked: All ranked items (sorted by score)
        test_results: Optional test results from agent testing
        run_date: Date for the digest
        max_items: Max items to include in the digest

    Returns:
        Markdown string
    """
    run_date = run_date or date.today()

    sections = []

    # Header
    sections.append(f"# AI News Digest — {run_date.strftime('%B %d, %Y')}")
    sections.append("")

    # Summary stats
    sources = set()
    for r in ranked:
        src = r.item.raw_data.get("all_sources", [r.item.source.value])
        sources.update(src if isinstance(src, list) else [src])

    sections.append(
        f"> **{len(ranked)}** items from **{len(sources)}** sources"
        f"{f' | **{len(test_results)}** tools tested' if test_results else ''}"
    )
    sections.append("")

    # Tested & Approved tools (if agent testing ran)
    if test_results:
        passed = [r for r in test_results if r.verdict == TestVerdict.PASS]
        if passed:
            sections.append("## Recommended Tools")
            sections.append("")
            for r in passed:
                item = r.item.item
                sections.append(f"### [{item.title}]({item.url})")
                sections.append(f"**Score:** {r.item.total_score}/40 | "
                              f"**Install:** `{r.install_command}` | "
                              f"**Verdict:** PASS")
                sections.append("")
                sections.append(f"{r.evaluation}")
                if r.security_concerns:
                    sections.append(f"\n> **Security:** {', '.join(r.security_concerns)}")
                if r.recommended_config.get("mcp_config"):
                    sections.append(f"\n**MCP Config:**")
                    sections.append(f"```json\n{_format_json(r.recommended_config['mcp_config'])}\n```")
                sections.append("")

        failed = [r for r in test_results if r.verdict == TestVerdict.FAIL]
        if failed:
            sections.append("## Tested but Not Recommended")
            sections.append("")
            for r in failed:
                sections.append(f"- **{r.item.item.title[:60]}** — {r.evaluation[:100]}")
            sections.append("")

    # Top Picks (by LLM score)
    sections.append("## Top AI News")
    sections.append("")

    # Skip items already shown in tested section
    tested_urls = {r.item.item.url for r in (test_results or [])}
    top_items = [r for r in ranked if r.item.url not in tested_urls][:max_items]

    for i, r in enumerate(top_items, 1):
        item = r.item
        source_list = item.raw_data.get("all_sources", [item.source.value])
        if isinstance(source_list, list):
            source_str = ", ".join(source_list)
        else:
            source_str = item.source.value

        sections.append(f"### {i}. [{item.title}]({item.url})")
        sections.append(
            f"**Score:** {r.total_score}/40 | "
            f"**Sources:** {source_str} | "
            f"**Community:** {item.score}"
        )
        if r.reasoning and r.reasoning != "Scored via basic heuristics (no LLM)":
            sections.append(f"\n{r.reasoning}")
        sections.append("")

    # Footer
    sections.append("---")
    sections.append(f"*Generated by [AI News Automation](https://github.com/ai-news-automation) on {run_date}*")

    return "\n".join(sections)


def save_digest(content: str, run_date: date | None = None) -> Path:
    """Save digest to output directory."""
    run_date = run_date or date.today()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    filename = f"{run_date}.md"
    filepath = OUTPUT_DIR / filename
    filepath.write_text(content)

    logger.info(f"Saved digest to {filepath}")
    return filepath


def _format_json(data: dict) -> str:
    import json
    return json.dumps(data, indent=2)
